name: Test, Build, and Deploy Voicehere

on:
  push:
    branches: [main]

jobs:
  test-build-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Display directory structure
        run: ls
        working-directory: frontend

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend
