name: Test, Build, and Deploy Voicehere

on:
  push:
    branches: [main]

jobs:
  test-build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Display directory structure
        run: ls
        working-directory: frontend

      - name: Testing Build
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build
